// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwwgsF-_-qzhLnJWir9bduS9b4Qo9tw6s',
    appId: '1:659587312091:android:98a4ed5c7e66406bc41ffe',
    messagingSenderId: '659587312091',
    projectId: 'hadith-reader-8034f',
    storageBucket: 'hadith-reader-8034f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3XCpmMxdyBnsWCSp-2_H-qdN8oitblDs',
    appId: '1:659587312091:ios:f1f23bfbadceb472c41ffe',
    messagingSenderId: '659587312091',
    projectId: 'hadith-reader-8034f',
    storageBucket: 'hadith-reader-8034f.firebasestorage.app',
    iosBundleId: 'com.example.hadithReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3XCpmMxdyBnsWCSp-2_H-qdN8oitblDs',
    appId: '1:659587312091:ios:f1f23bfbadceb472c41ffe',
    messagingSenderId: '659587312091',
    projectId: 'hadith-reader-8034f',
    storageBucket: 'hadith-reader-8034f.firebasestorage.app',
    iosBundleId: 'com.example.hadithReader',
  );
}
